name: Python script

on:
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Run Python script
      run: python main.py
            git config --global user.email "${{secrets.email}}"
            git config --global user.name "${{secrets.name}}"
            git add .
            git commit -m "Update weather last time"
            git push origin main
