name: Python script

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Pull latest changes
      uses: actions/checkout@v2
      with:
        ref: main # Replace 'main' with the name of your branch
        fetch-depth: 0
      
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install requests module
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Run Python script And Commit
      run:  |
        python main.py
        git config --global user.email "${{ secrets.USER_EMAIL }}"
        git config --global user.name "${{ secrets.USER_NAME }}"
        git add README.md
        git commit -m "Update weather"
        git push origin main
